# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

includes:
  fargate:
    taskfile: ./Fargate
    internal: true
    dir: ./Fargate

tasks:
   deploy:
    desc: Deploy the infrastructure
    cmds:
      - task: fargate:init
      - task: fargate:validate
      - task: fargate:plan 
        vars:
          CLI_ARGS: '-target=module.ecr-repos'
      - task: fargate:apply
      - task: fargate:plan 
        vars:
          CLI_ARGS: '-target=null_resource.build_and_push_images'
      - task: fargate:apply
      - task: fargate:plan
      - task: fargate:apply